.PHONY: clean All

All:
	@echo "----------Building project:[ StringStreams - Debug ]----------"
	@cd "StringStreams" && "$(MAKE)" -f  "StringStreams.mk"
clean:
	@echo "----------Cleaning project:[ StringStreams - Debug ]----------"
	@cd "StringStreams" && "$(MAKE)" -f  "StringStreams.mk" clean
