.PHONY: clean All

All:
	@echo "----------Building project:[ FriendsOfClass - Debug ]----------"
	@cd "FriendsOfClass" && "$(MAKE)" -f  "FriendsOfClass.mk"
clean:
	@echo "----------Cleaning project:[ FriendsOfClass - Debug ]----------"
	@cd "FriendsOfClass" && "$(MAKE)" -f  "FriendsOfClass.mk" clean
