.PHONY: clean All

All:
	@echo "----------Building project:[ FactorialRecursion - Debug ]----------"
	@cd "FactorialRecursion" && "$(MAKE)" -f  "FactorialRecursion.mk"
clean:
	@echo "----------Cleaning project:[ FactorialRecursion - Debug ]----------"
	@cd "FactorialRecursion" && "$(MAKE)" -f  "FactorialRecursion.mk" clean
