.PHONY: clean All

All:
	@echo "----------Building project:[ NumberTest - Debug ]----------"
	@cd "NumberTest" && "$(MAKE)" -f  "NumberTest.mk"
clean:
	@echo "----------Cleaning project:[ NumberTest - Debug ]----------"
	@cd "NumberTest" && "$(MAKE)" -f  "NumberTest.mk" clean
