.PHONY: clean All

All:
	@echo "----------Building project:[ Section8Challenge - Debug ]----------"
	@cd "Section8Challenge" && "$(MAKE)" -f  "Section8Challenge.mk"
clean:
	@echo "----------Cleaning project:[ Section8Challenge - Debug ]----------"
	@cd "Section8Challenge" && "$(MAKE)" -f  "Section8Challenge.mk" clean
