.PHONY: clean All

All:
	@echo "----------Building project:[ interfaces-complete - Debug ]----------"
	@cd "interfaces-complete" && "$(MAKE)" -f  "interfaces-complete.mk"
clean:
	@echo "----------Cleaning project:[ interfaces-complete - Debug ]----------"
	@cd "interfaces-complete" && "$(MAKE)" -f  "interfaces-complete.mk" clean
