.PHONY: clean All

All:
	@echo "----------Building project:[ pyramidAssignment - Debug ]----------"
	@cd "pyramidAssignment" && "$(MAKE)" -f  "pyramidAssignment.mk"
clean:
	@echo "----------Cleaning project:[ pyramidAssignment - Debug ]----------"
	@cd "pyramidAssignment" && "$(MAKE)" -f  "pyramidAssignment.mk" clean
